### ISSUE TITLE
Unhandled Exception: RangeError (index): Invalid value: Not in range 0..15, inclusive: 16

### ISSUE THREAD

**Issue by rainmeterLotus** [nervouself/quantize_dart#1]
E/flutter (14527): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: RangeError (index): Invalid value: Not in range 0..15, inclusive: 16
E/flutter (14527): #0      List.[] (dart:core-patch/growable_array.dart:149:60)
E/flutter (14527): #1      _medianCutApply.doCut (package:quantize_dart/quantize_dart.dart:428:30)
E/flutter (14527): #2      _medianCutApply (package:quantize_dart/quantize_dart.dart:456:67)
E/flutter (14527): #3      quantize.iter (package:quantize_dart/quantize_dart.dart:502:20)
E/flutter (14527): #4      quantize (package:quantize_dart/quantize_dart.dart:519:7)

**Comment by jzsn2018** [comment]
I have the same problem as you. Have you solved it？

**Comment by nervouself** [comment]
I will check it later

**Comment by jzsn2018** [comment]
> I will check it later

Thank you

**Comment by nervouself** [comment]
Can you provide more information? Like your os or your platform or the list/picture?

**Comment by nervouself** [comment]
You can install the latest version to check if it is resolved.
